id = "poimandres"
name = "poimandres"
version = "0.0.4"
schema_version = 1
description = "poimandres themes"
repository = "https://github.com/mshaugh/poimandres.zed"
authors = ["mshaugh <max@mshaugh.com>", "luk4h <luizmarcondes@lgvm.dev>"]
themes = ["themes/poimandres-storm.json", "themes/poimandres.json", "themes/poimandres-white.json"]
languages = []

[lib]

[grammars]

[language_servers]

[slash_commands]

[indexed_docs_providers]
