[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 80 , lines = 26}
padding = { x = 8 , y = 8 }
dynamic_padding = true
decorations = "Transparent"
opacity = 0.95

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
