id = "sql"
name = "SQL"
version = "1.1.2"
schema_version = 1
description = "SQL language support."
repository = "https://github.com/nervenes/zed-sql"
authors = ["nervenes", "notpeter", "phileix", "tammyxiong"]
themes = []
languages = ["languages/sql"]

[lib]

[grammars.sql]
repository = "https://github.com/nervenes/tree-sitter-sql"
rev = "6dfca8b6dcb196d943c10e9cabab25e60232d332"

[language_servers]

[slash_commands]

[indexed_docs_providers]
