id = "emmet"
name = "Emmet"
version = "0.0.3"
schema_version = 1
description = "Emmet support"
repository = "https://github.com/zed-industries/zed"
authors = ["Piotr Osiewicz <piotr@zed.dev>"]
themes = []
languages = []

[lib]
kind = "Rust"
version = "0.0.4"

[grammars]

[language_servers.emmet-language-server]
language = "HTML"
languages = ["HTML", "PHP", "ERB", "JavaScript", "TSX", "CSS"]

[language_servers.emmet-language-server.language_ids]
TSX = "typescriptreact"
HTML = "html"
PHP = "php"
JavaScript = "javascriptreact"
CSS = "css"
ERB = "eruby"
