id = "catppuccin"
name = "Catppuccin"
version = "0.2.19"
schema_version = 1
description = "🦀 Soothing pastel theme for Zed"
repository = "https://github.com/catppuccin/zed"
authors = ["Catppuccin <releases@catppuccin.dev>"]
themes = ["themes/catppuccin-no-italics-mauve.json", "themes/catppuccin-mauve.json"]
languages = []

[lib]

[grammars]

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
