name = "Git Config"
grammar = "git_config"
path_suffixes = [
  # Refer to https://github.com/neovim/neovim/blob/191cca2566a8afe2b2f2744f3eb763d810cc416c/runtime/lua/vim/filetype.lua#L1294-L1295C5
  ".gitconfig",
  ".gitmodules"
]
line_comments = ["; "]
autoclose_before = "]"
brackets = [
  { start = "[", end = "]", close = true, newline = false }
]
