# To be honest, I rarely use git_rebase, so maybe I'm overlooking something?

name = "Git Rebase"
grammar = "git_rebase"
path_suffixes = [
  # Refer to https://github.com/neovim/neovim/blob/191cca2566a8afe2b2f2744f3eb763d810cc416c/runtime/lua/vim/filetype.lua#L1299C5-L1299C20
  "git-rebase-todo",
]
line_comments = ["#"]
brackets = []
