id = "docker-compose"
name = "Docker Compose"
version = "0.1.0"
schema_version = 1
description = "Syntax highlighting for Docker Compose files"
repository = "https://github.com/eth0net/zed-docker-compose"
authors = ["eth0net <eth0net@pm.me>"]
themes = []
languages = []

[lib]
kind = "Rust"
version = "0.0.6"

[grammars]

[language_servers.docker-compose]
language = "YAML"
languages = []

[language_servers.docker-compose.language_ids]
